version: "3.9"
   
services:
  redis-stage:
    image: arm32v7/redis
    volumes:
      - ./redis/data:/data
    ports:
      - '6380:6379'
    command: redis-server --appendonly yes --maxmemory 512mb --tcp-backlog 128
    restart: always
  server-stage:
    image: einkaufsliste-stage/webapp
    environment:
      - DEPLOY_ENVIRONMENT=stage
    build: .
    volumes:
      - ./app:/app
    ports:
      - "8082:80"
    restart: always
    depends_on:
      - redis-stage


