version: "3.9"
   
services:
  redis:
    image: arm32v7/redis
    volumes:
      - ./redis/data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --tcp-backlog 128
    restart: always
  server:
    image: einkaufsliste-multiuser-test/webapp
    environment:
      - DEPLOY_ENVIRONMENT=test
    build: .
    volumes:
      - ./app:/app
    ports:
      - "8084:80"
    restart: always
    depends_on:
      - redis


