version: "3.9"
   
services:
  redis:
    image: arm32v7/redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_MASTER_HOST=${REDIS_MASTER_HOST:-}
      - REDIS_MASTER_PORT=${REDIS_MASTER_PORT:-}
    volumes:
      - ./redis/data:/data
    command: >
      /bin/sh -c "
      if [ \"$REDIS_MASTER_HOST\" = \"\" ]; then
        redis-server --appendonly yes --maxmemory 512mb --tcp-backlog 128
      else
        redis-server --appendonly yes --maxmemory 512mb --tcp-backlog 128 --replicaof ${REDIS_MASTER_HOST} ${REDIS_MASTER_PORT}
      fi
      "
    restart: unless-stopped

  redis-sentinel:
    image: arm32v7/redis
    ports:
      - "26379:26379"
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER_TIMEOUT=10000
      - SENTINEL_ANNOUNCE_IP=${REDIS_HOST_IP}
      - SENTINEL_ANNOUNCE_PORT=${REDIS_HOST_PORT}
    command: redis-server /etc/redis/sentinel.conf --sentinel
    restart: unless-stopped
    volumes:
      - ./sentinel-config:/etc/redis
      - redis-sentinel-1-data:/data/sentinel
    depends_on:
      - redis

  server:
    image: einkaufsliste-multiuser/webapp
    environment:
      - DEPLOY_ENVIRONMENT=production
    build: .
    volumes:
      - ./app:/app
    ports:
      - "8083:80"
    restart: always
    depends_on:
      - redis

  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    depends_on:
      - server
    restart: always

volumes:
  redis-sentinel-1-data:


